#pragma once

#include "../../src/curve.h"
#include "../../src/helper.h"
#include "../../src/matrix.h"
#include "../../src/matrix_checks.h"
#include "../../src/matrix_decompositions.h"
#include "../../src/matrix_eigen.h"
#include "../../src/matrix_general.h"
#include "../../src/matrix_operators.h"
#include "../../src/matrix_transformations.h"
#include "../../src/vector.h"
#include "../../src/vector_checks.h"
#include "../../src/vector_general.h"
#include "../../src/vector_operators.h"
#include "../../src/vertex.h"